services:
  db:
    image: postgres:15-alpine
    container_name: webhook_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: webhook_app_container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/webhook_db
      WEBHOOK_SECRET: Yara-Mila2024
      PORT: 3000
    depends_on:
      - db

volumes:
  postgres_data:
